### ISSUE TITLE
next版本8.6.1，使用插件后代码块的文字高亮颜色被改变

### ISSUE THREAD

**Issue by Ubivision** [rqh656418510/hexo-next-darkmode#1]
![image](https://user-images.githubusercontent.com/39018918/126961675-5fa6cde1-5771-412a-8610-12110173ce11.png)
这是自带的黑暗模式下的代码块
![image](https://user-images.githubusercontent.com/39018918/126961842-ffff9ab5-5742-4bdb-81e6-0ace66eeb9da.png)
这是使用插件后的代码块，我也没有找到在哪里可以更改文字颜色的

**Comment by rqh656418510** [comment]
这是因为切换到暗黑模式后，插件默认添加的新 CSS 样式生效了，可以试试手动添加以下样式，取消代码块的颜色变更：

``` css
.darkmode--activated code {
  color: unset;
  background: transparent;
}
```

还有插件本身是支持自定义样式的，自定义样式的教程可以参考 [这里](https://github.com/rqh656418510/hexo-next-darkmode/blob/main/README_CN.md#自定义样式)
