### ISSUE TITLE
next主题公安备案图标显示异常

### ISSUE THREAD

**Issue by ours1984** [rqh656418510/hexo-next-darkmode#4]
darkmode-ignore样式导致foot里的img自动换行了
参考 <https://blog.ours1984.top/posts/darkmode/>

**Comment by rqh656418510** [comment]
你自己添加样式解决了吗？因为刚访问你的博客，没看到公安备案图标自动换行了。

**Comment by rqh656418510** [comment]
谢谢反馈，公安备案图标显示异常的 Bug 已修复，卸载插件重新安装即可生效。

**Comment by rqh656418510** [comment]
另外，不建议直接去掉下面的 CSS 样式，因为这可能会导致文章里的图片无法居中显示。

``` css
img, .darkmode-ignore {
  display: flex !important;
}
```
